version: "3"
services:
  db:
    image: postgres:16.0
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: demo
    ports:
      - "5432:5432"
    volumes:
      - ./db/tables.sql:/docker-entrypoint-initdb.d/1.sql
      - ./db/data.sql:/docker-entrypoint-initdb.d/2.sql